---- V1 -------------
# The content of the Docker file is used the base image nginx to create the container.
From nginx:latest
# The content of the below line is :- created a file "index.html" in my local system and same file copied to the path "/usr/share/nginx/html/". 
# This is the default host location of the nginx server.
copy index.html /usr/share/nginx/html/index.html

